# Copyright (c) 2026, Ascra Technologies and contributors
# License: MIT

STATUTORY_WAGE_CEILING = 15000
EPF_EMPLOYEE_RATE = 0.12
MAX_VPF_PERCENT_OF_WAGES = 1.0
VPF_ADDITIONAL_SALARY_YEARS = 10

PF_CONTRIBUTION_STATUTORY = "Statutory Minimum"
PF_CONTRIBUTION_VOLUNTARY_FIXED = "Voluntary Fixed Amount"
PF_CONTRIBUTION_VOLUNTARY_FULL_BASIC = "Voluntary on Full Basic"
